### ISSUE TITLE
SystemD Service Files to properly start cuckoo components

### ISSUE THREAD

**Issue by Jack28** [scVENUS/PeekabooAV-Installer#20]
Here is a description with the proper way to start cuckoo, api, web ui, processors, router:
https://github.com/cuckoosandbox/cuckoo/issues/2025

We should adapt our unit files accordingly.

@michaelweiser what's your optinion on this?

**Comment by michaelweiser** [comment]
Agreed. Went ahead and merged the knowledge we (or at least I) gained about Cuckoo in recent months with the upstream systemd unit examples. I did not actually try to understand why we would want to maybe employ supervisord (it's not clear to me from the Cuckoo issue) and just went ahead and adjusted/added the systemd units (for now).
