### ISSUE TITLE
Executable cuckoo is not installed to /usr/local/bin/cuckoo

### ISSUE THREAD

**Issue by Clevero** [scVENUS/PeekabooAV-Installer#29]
Currently setting up a new instance of peekaboo.

Going through the "Check the components" section and tried to execute 
```su -c "cuckoo" peekaboo```

But it seems that the executable cuckoo is not installed to /usr/local/bin/cuckoo and cuckoo could not be found. Executing ```bash su -c "/opt/cuckoo/bin/cuckoo" peekaboo``` is working though
Is this intented?
If so, I would update the documentation

**Comment by michaelweiser** [comment]
Hi @Clevero, thanks for reporting this.

Indeed this is due to the switch to virtualenvs and related to PeekabooAV#55. I will update the documentation.

**Comment by michaelweiser** [comment]
This is done now. Closing.
