### ISSUE TITLE
Release tarball does not include PeekabooAV submodule content

### ISSUE THREAD

**Issue by michaelweiser** [scVENUS/PeekabooAV-Installer#36]
The tarballs auto-generated by GitHub do not contain submodule content. Since they're not git repos either, `git submodule` commands can not be used either. We need to get the submodule content into the tarball.

**Comment by michaelweiser** [comment]
There seems no easy way to do this with only GitHub mechanics. A plethora of other projects have run into this as well. They eventually all switched to attaching custom-built tarballs to releases that include the submodules.

Perhaps we should consider going back to installing releases from PyPI and only optionally go looking for a manually provided PeekabooAV subdirectory for testing inbetween releases? What's your take on this, @Jack28?

**Comment by michaelweiser** [comment]
Just rediscovered a (seemingly? :) clever idea I had on this earlier: https://github.com/scVENUS/PeekabooAV-Installer/issues/9#issuecomment-418710531.

**Comment by Jack28** [comment]
Agreed.
To look for the subdirectory instead of the branch is more visible and less likely to go wrong though.

**Comment by michaelweiser** [comment]
Agreed. Will come up with apropriate detection of the directory in the ansible playbook and otherwise revert to PyPI.

**Comment by Jack28** [comment]
NOTE: [pstrap.sh](https://github.com/scVENUS/PeekabooAV-Installer/blob/cfad3c136a22214877d7391cfadf54b92be07bd4/pstrap.sh#L16) doesn't include `--recurse-submodules`
