### ISSUE TITLE
peekabooStatus.sh needs to be updated

### ISSUE THREAD

**Issue by Jack28** [scVENUS/PeekabooAV-Installer#38]
https://github.com/scVENUS/PeekabooAV-Installer/blob/cfad3c136a22214877d7391cfadf54b92be07bd4/utils/peekabooStatus.sh

`peekabooStatus.sh` doesn't work with current version, neither Peekaboo nor database.

Documentation has to be added.

**Comment by michaelweiser** [comment]
Gave this a quick once-over with my knowledge of what I did to the database schema: See https://github.com/michaelweiser/PeekabooAV-Installer/commit/e93ed286d8b0b69659815bd0adbed10edfc84bab for your consideration.
