### ISSUE TITLE
add hint to error message

### ISSUE THREAD

**Issue by Clevero** [scVENUS/PeekabooAV-Installer#5]
I would like to make a pull request. But after going through the contributing guidelines, I don't know if this change is valuable enough

https://github.com/Clevero/PeekabooAV-Installer/commit/255be807e6780af3ae6078cb0c66481ee344b63b

**Comment by Jack28** [comment]
Hi, thank you for your contribution.
Please file a pull request.
Always!

**Comment by Clevero** [comment]
#6
