### ISSUE TITLE
gcc missing

### ISSUE THREAD

**Issue by Jack28** [scVENUS/PeekabooAV-Installer#55]
`gcc` is not installed.
Therefore building failes for some python modules.

Adding package `gcc` in "Install basic tools" solves this.

**Comment by michaelweiser** [comment]
The install docs of Peekaboo list `build-essential` which pulls in gcc. But our installer doesn't install it. The minimal Dockefile ironically does. How did we miss this up until now? :)

I'm poking around in there with #53 anyway. Shall I push a patch?

**Comment by michaelweiser** [comment]
Is this with current master or with #53?

**Comment by Jack28** [comment]
This is with #53

**Comment by michaelweiser** [comment]
Right. We should discuss it in #53 then. Will close here to avoid confusion.
