### ISSUE TITLE
Cuckoo API bearer token not set when using the most recent PeekabooAV version

### ISSUE THREAD

**Issue by JannisTriesToCode** [scVENUS/PeekabooAV-Installer#56]
```
git clone https://github.com/scvenus/peekabooav-installer
cd peekabooav-installer/
git clone https://github.com/scvenus/peekabooav PeekabooAV
./PeekabooAV-install.sh
```

The generated peekaboo.conf is still the one without the api_token attribute. This is probably due to the installer using the .conf from the PeekabooAV-Installer repo and not the one from the PeekabooAV repo.

This issue appears to be related:
https://github.com/scVENUS/PeekabooAV-Installer/issues/43

**Comment by michaelweiser** [comment]
Yes, we're on it. #53 should fix it once I've figured out a way to either make cuckoo accept our generated token or extract cuckoo's token from its `cuckoo.conf` and transplant that into `peekaboo.conf`. Should be no rocket science either way.
