### ISSUE TITLE
Release v2.0 matching Peekaboo 2.0

### ISSUE THREAD

**Issue by Jack28** [scVENUS/PeekabooAV-Installer#63]
Update version tags, configurations and references to use PeekabooAV 2.0 by default.
Plus testing ;-)

**Comment by michaelweiser** [comment]
Awesome stuff! Champagne corks flying here. ;) Regarding the installer update to the new release: I had regularly synced the configs with PeekabooAV master already so the delta should be small (if at all). The installer should pick the latest release version from PyPI automatically, which is 2.0 now. So this shouldn't be a big thing: I find `1.7` in `README.md` and `pstrap.sh` only.

**Comment by Jack28** [comment]
Nothing more to change.
I've just released 2.0
