### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by furban1** [scVENUS/PeekabooAV-Installer#69]
Hi,

just tried to create a new test installation on a brand new Ubuntu 18.04 server installation but the PeekabooAV-install.sh fsileed with this error message. Any idea?

TASK [Work around flask werkzeug version mismatch] *****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/opt/cuckoo/bin/pip2 install werkzeug==0.16.1", "msg": "stdout: Collecting werkzeug==0.16.1\n\n:stderr:   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f864e20e450>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/werkzeug/\n  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f864e20e590>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/werkzeug/\n  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f864e20e690>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/werkzeug/\n  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f864e20e890>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/werkzeug/\n  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f864e20ea10>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/werkzeug/\n  Could not find a version that satisfies the requirement werkzeug==0.16.1 (from versions: )\nNo matching distribution found for werkzeug==0.16.1\n"}
        to retry, use: --limit @/root/peekabooav-installer/PeekabooAV-install.retry

PLAY RECAP *********************************************************************************************
localhost                  : ok=18   changed=4    unreachable=0    failed=1   

ERROR: 'ansible-playbook' failed. Please fix manually

Greetings

Frank

**Comment by furban1** [comment]
I think I found the problem. The command

"/opt/cuckoo/bin/pip2 install werkzeug==0.16.1" 
does not work in my environment because I'm using a Proxy

Using the command
/opt/cuckoo/bin/pip2 --proxy x.x.x.x:3128 install werkzeug==0.16.1
will bring me one step ahead.

Greetings

Frank

**Comment by michaelweiser** [comment]
Hi @furban1, the error message indicates a networking problem, particularly with name resolution:
```
Failed to establish a new connection: [Errno -2] Name or service not known
```
I just ran the installer on a fresh 18.04 VM without this error. Since the werkzeug workaround is the first call to pip in the installer but we do other network access by installing packages with apt before that, it seems somewhat specific to PyPI. You can try the pip command (likely *any* pip command) manually to narrow down the cause:
```
/opt/cuckoo/bin/pip2 install werkzeug==0.16.1
```

**Comment by michaelweiser** [comment]
@furban1: race condition hit ;)

You should also be able to use environment variables HTTP_PROXY and friends when running the installer so you don't need to iterate through all the pip commands hitting this error.

Will close for now.

**Comment by furban1** [comment]
Thanks for the fast answer :)
Everything else works with the proxy. Only the /opt/cuckoo/bin/pip2  does not work. I'm still searching the right way to tell pip2 also to using the Proxy

**Comment by furban1** [comment]
OK. Thanks. Found it 
sudo vi /etc/environment
Thanks for teh help. You can close now
