### ISSUE TITLE
Remove duplicate of amavis plugin

### ISSUE THREAD

**Issue by michaelweiser** [scVENUS/PeekabooAV-Installer#8]
Currently we have a copy of the amavis plugin in the installer that needs to be kept in sync with the main instance in PeekabooAV repo. We should eliminate the local copy and take the plugin directly from the Peekaboo installation.

**Comment by Jack28** [comment]
We can not rely on those files beeing at that location. I'd rather have the PeekabooAV repository as a submodule of the Installer repository.
Not sure if a submodule can be checked out to a specific tag/release (branch is possible).

**Comment by SebastianDeiss** [comment]
I seems a lot more simple to me to ship the AMaViSd plugin with the PIP package and then copy it to ``/etc/amavis/conf.d``, rather than using a git submodule.

**Comment by michaelweiser** [comment]
I concur: For released Peekaboo versions we should use the plugin from the distribution. If we discover an error in it, we obviously make a new release of Peekaboo and update the installer to install that new release. The case of developing the installer and testing it with unreleased versions of the plugin in preparation for the next peekaboo release is covered #9.

**Comment by michaelweiser** [comment]
> We can not rely on those files beeing at that location.

Why's that? Doesn't the installer direct pip to install it there? If not, can the installer do so so we can rely on the location? IMO that would be an acceptable tradeoff to get a reproducible installation in any case.

Otherwise: Can ansible interview pip for the location it installed the peekaboo package to so it knows where to look for the plugin?
