### ISSUE TITLE
Allow testing the installer with unreleased Peekaboo versions

### ISSUE THREAD

**Issue by michaelweiser** [scVENUS/PeekabooAV-Installer#9]
We should enhance the installer so it can install unreleased Peekaboo versions, e.g. directly from the git repo. The ansible playbook could have a flag for that. Maybe the PeekabooAV repo could be a submodule or the ansible playbook checks it out into a temporary directory itself.

**Comment by Jack28** [comment]
This is very similar to #8 I agree.

The installer contains a lot ot files that can be used without running the installer itself therefore I would prefer to use a submodule. It's even possible to specify the corresponding release branch to clone the matching version.

It's not good practice to change the submodule config before doing the release commit and changing it back to master afterwards I guess. Any ideas on that?

**Comment by michaelweiser** [comment]
From what I know about submodules in git, a submodule is normally fixed at a specific commit and you have to update it manually. The information to what commit you've updated the submodule can then be commited to the superproject.

This should for the most part fit the normal installer/peekaboo-core development interaction: If you want to test the installer with a more current devel version of peekaboo you update the submodule, test and if it works, you commit that new upstream peekaboo repo reference.

Do you plan to switch to a git submodule for release deployments as well? In that case you could branch off an installer release branch matching and referencing the peekaboo release commit and just never update it after.

**Comment by SebastianDeiss** [comment]
A simple apporach to test the installer with pre-releases would be the following:

* Create a branch for each release of PeekabooAV, that installs that specific version. We already create release branches for PeekabooAV, so why shouldn't we do it for the installer too?
* On ``master`` keep an installer, that installs the current DEV version of PeekabooAV (``master`` branch).

**Comment by michaelweiser** [comment]
@SebastianDeiss: Total agreement.

**Comment by Jack28** [comment]
970661cf2d72d64eb9c1b73cc8aa8d9b2f20c032 installs what is inside PeekabooAV submodule directory
